trigger:
- $(triggerBranch)

resources:
- repo: self

variables:
  triggerBranch: main
  imageRepo: 'mkivo/node-mongoose-prototype'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Connection'
        repository: $(imageRepo)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)




  


