trigger:
- multi-stage

resources:
- repo: self

variables:
  imageRepo: 'mkivo/node-mongoose-prototype'
  tag: 'multi-variables' #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Connection'
        repository: $(imageRepo)
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        tags: |
          $(tag)



  