trigger:
- refactor

resources:
- repo: self

variables:
  imageRepo: 'mkivo/node-mongoose-prototype'
  tag: refactor #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Deployments Service Connection'
        KeyVaultName: 'nmp-pipeline-keys'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: CmdLine@2
      displayName: Write to file
      inputs:
        script: |
          echo $(CONN-STR)
          echo $(CONN-STR) > env.txt
          cat env.txt

    - task: CopyFiles@2
      inputs:
        Contents: 'env.txt'
        TargetFolder: '$(Build.SourcesDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish env variables
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Connection'
        repository: $(imageRepo)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)




    


