version: '3'

services:
  node-app:
    image: node:latest
    networks:
      - local-mongodb-server_mongo-network
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: npm start

networks:
  local-mongodb-server_mongo-network:
    external: true
