apiVersion: v1
kind: Service
metadata:
  name: node-mongoose-prototype-service
  labels:
    app: mern-k8s
    component: back
spec:
  type: LoadBalancer
  selector:
    component: back
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http